### ISSUE TITLE
Error Thrown When Running Examples During Heartbeat

### ISSUE THREAD

**Issue by ButchMonkey** [d-pollard/Pokemon-GO-node-api#5]
Hey, can you shed some light on this please? 
When running pokeio examples this error is thrown.

```

/home/ubuntu/workspace/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:1801
                throw Error("Illegal value for "+self.toString(true)+" of type "+self.type.name+": "+val+" ("+msg+")");
                ^

Error: Illegal value for [object Object] of type uint64: object (not convertible to Long)
    at Error (native)
    at fail (/home/ubuntu/workspace/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:1801:23)
    at ProtoBuf.Reflect.ElementPrototype.verifyValue (/home/ubuntu/workspace/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:1841:29)
    at ProtoBuf.Reflect.FieldPrototype.verifyValue (/home/ubuntu/workspace/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:3455:43)
    at MessagePrototype.set (/home/ubuntu/workspace/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2475:59)
    at MessagePrototype.set (/home/ubuntu/workspace/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2466:38)
    at Message (/home/ubuntu/workspace/node_modules/pokemon-go-node-api/node_modules/protobufjs/dist/protobuf.js:2395:34)
    at Pokeio.self.Heartbeat (/home/ubuntu/workspace/node_modules/pokemon-go-node-api/poke.io.js:256:24)
    at null._repeat (/home/ubuntu/workspace/Pokemon-GO-node-api/exampleFort.js:40:11)
    at wrapper [as _onTimeout] (timers.js:275:11)
```

When Running pokego examples, I get

```
/home/ubuntu/workspace/Pokemon-GO-node-api/pokego.js:22
const {RequestEnvelop, ResponseEnvelop} = pokemonProto;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/Pokemon-GO-node-api/ExampleInventory.js:12:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by d-pollard** [comment]
It looks like you need to upgrade to the latest version of node.

**Comment by ButchMonkey** [comment]
Updating Node Fixed the issue. Thanks

However, now is throwing the following issue

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/workspace/Pokemon-GO-node-api/pokego.js:3:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by katp4** [comment]
Have you run npm install?

**Comment by ButchMonkey** [comment]
yes

**Comment by d-pollard** [comment]
do `npm install request`
