### ISSUE TITLE
Random -> TypeError: Cannot read property 'username' of null

### ISSUE THREAD

**Issue by FabioAntunes** [d-pollard/Pokemon-GO-node-api#6]
Sometimes I'm getting this:

```
[i] Received Google access token! {Expires: 1469838239}
[i] Received API Endpoint: https://pgorelease.nianticlabs.com/plfe/553/rpc
TypeError: Cannot read property 'username' of null
    at api_req.then (/home/fabio/playground/pokemon-go-map/node_modules/pokemon-go-node-api/pokego.js:260:16)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by d-pollard** [comment]
And the username is set?

**Comment by FabioAntunes** [comment]
Yep if I kill the server and start it again it works, it's doing this randomly.

**Comment by d-pollard** [comment]
Ill for sure take a look at it
